version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    image: ${APP_NAME}-frontend-grpc-dev
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
      - GRPC_WEB_URL=${GRPC_WEB_URL}
      - VUE_APP_GRPC_WEB_URL=${GRPC_WEB_URL}
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=500
      - WATCHPACK_POLLING=true
      - HMR_HOST=localhost
      - FAST_REFRESH=true
      - VUE_CLI_BABEL_TRANSPILE_MODULES=true

    volumes:
      - ./frontend/src:/app/src:delegated
      - ./frontend/public:/app/public:delegated
      - ./frontend/vue.config.js:/app/vue.config.js:delegated
      - ./frontend/tailwind.config.js:/app/tailwind.config.js:delegated
      - ./frontend/package.json:/app/package.json:delegated
      - ./proto:/app/proto:delegated
      - frontend-node-modules:/app/node_modules

    container_name: ${APP_NAME}-frontend-grpc-dev
    command: ["npm", "run", "serve"]
    stdin_open: true
    tty: true
    restart: unless-stopped

    depends_on:
      - backend-grpc-server

  backend-grpc-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile.dev
    image: ${APP_NAME}-backend-grpc-server-dev
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${GRPC_WEB_PORT}:${GRPC_WEB_PORT}"
    networks:
      - app-network
    environment:
      - PORT=${BACKEND_PORT}
      - WEB_PORT=${GRPC_WEB_PORT}
    container_name: ${APP_NAME}-backend-grpc-server-dev
    restart: unless-stopped

    volumes:
      - ./server:/app/server:delegated

volumes:
  frontend-node-modules:
    driver: local

networks:
  app-network:
    driver: bridge
    name: ${APP_NAME}-grpc-dev-network
