version: '3.8'

services:
  grpc-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "50051:50051"
    networks:
      - app-network
    environment:
      - PORT=50051

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - GRPC_SERVER_URL=grpc-server:50051
    depends_on:
      - grpc-server

networks:
  app-network:
    driver: bridge
