version: '3.8'

services:
  backend-grpc-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: ${APP_NAME}-backend-grpc-server
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${GRPC_WEB_PORT}:${GRPC_WEB_PORT}"
    networks:
      - app-network
    environment:
      - PORT=${BACKEND_PORT}
      - WEB_PORT=${GRPC_WEB_PORT}
    container_name: ${APP_NAME}-backend-grpc-server

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: ${APP_NAME}-frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app-network
    environment:
      - GRPC_WEB_URL=${GRPC_WEB_URL}
      - VUE_APP_GRPC_WEB_URL=${GRPC_WEB_URL}
      - GRPC_SERVER_URL=${BACKEND_HOST}:${BACKEND_PORT}
      - PORT=${FRONTEND_PORT}
    depends_on:
      - backend-grpc-server
    container_name: ${APP_NAME}-frontend

networks:
  app-network:
    driver: bridge
    name: ${APP_NAME}-network
