version: '3.8'

services:
  dev-environment:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: ${APP_NAME}-dev-environment
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${GRPC_WEB_PORT}:${GRPC_WEB_PORT}"
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      - "24678:24678"
    networks:
      - app-network-dev
    environment:
      - PORT=${BACKEND_PORT:-50051}
      - WEB_PORT=${GRPC_WEB_PORT:-8081}
      - BACKEND_PORT=${BACKEND_PORT:-50051}
      - GRPC_WEB_PORT=${GRPC_WEB_PORT:-8081}
      - BACKEND_HOST=${BACKEND_HOST:-localhost}
      - BACKEND_BASE_URL=${BACKEND_BASE_URL:-http://localhost:50051}
      - GRPC_WEB_URL=${GRPC_WEB_URL:-http://localhost:8081}
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - GO_ENV=development

      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - FRONTEND_HOST=${FRONTEND_HOST:-localhost}
      - FRONTEND_PROTOCOL=${FRONTEND_PROTOCOL:-http}
      - BASE_URL=${BASE_URL:-http://localhost:3000/}
      - VUE_APP_GRPC_WEB_URL=${GRPC_WEB_URL:-http://localhost:8081}
      - NODE_ENV=development

      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true

      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - ./server:/app/server:cached
      - ./frontend:/app/frontend:cached
      - ./proto:/app/proto:cached

      - ./dev-start.sh:/app/dev-start.sh:ro

      - dev-go-cache:/go/pkg/mod
      - dev-node-cache:/app/frontend/node_modules
      - dev-webpack-cache:/app/frontend/node_modules/.cache

      - /app/server/tmp
      - /app/frontend/dist
      - /app/frontend/node_modules/.cache/webpack

    container_name: ${APP_NAME}-dev-environment
    restart: unless-stopped
    working_dir: /app

    healthcheck:
      test: |
        # Check proto files exist
        test -f /app/frontend/src/proto/user_grpc_web_pb.js &&
        test -f /app/frontend/src/proto/user_pb.js &&
        test -f /app/server/pb/user.pb.go &&
        test -f /app/server/pb/user_grpc.pb.go &&
        # Check services are responding
        curl -f http://localhost:${FRONTEND_PORT:-3000} &&
        curl -f http://localhost:${GRPC_WEB_PORT:-8081} || exit 1
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 180s

    init: true

    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

    labels:
      - "dev.hotreload=true"
      - "dev.environment=development"

networks:
  app-network-dev:
    driver: bridge
    name: ${APP_NAME}-network-dev

volumes:
  dev-go-cache:
    name: ${APP_NAME}-dev-go-cache
    driver: local
  dev-node-cache:
    name: ${APP_NAME}-dev-node-cache
    driver: local
  dev-webpack-cache:
    name: ${APP_NAME}-dev-webpack-cache
    driver: local
