version: '3.8'

services:
  backend-grpc-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: ${APP_NAME}-backend-grpc-server:${IMAGE_TAG:-latest}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"  # Standard gRPC (50051:50051)
      - "8081:8081"                        # ✅ FIXED: gRPC-Web Port korrekt unter ports
    networks:
      - app-network
    environment:
      - PORT=${BACKEND_PORT}               # Standard gRPC Port (50051)
      - WEB_PORT=8081                      # gRPC-Web Port (8081)
    container_name: ${APP_NAME}-backend-grpc-server

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: ${APP_NAME}-frontend:${IMAGE_TAG:-latest}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app-network
    environment:
      # ✅ FIXED: Für gRPC-Web den korrekten Port verwenden
      - VUE_APP_GRPC_WEB_URL=http://localhost:8081
      - GRPC_SERVER_URL=${BACKEND_HOST}:${BACKEND_PORT}
      - PORT=${FRONTEND_PORT}
    depends_on:
      - backend-grpc-server
    container_name: ${APP_NAME}-frontend

networks:
  app-network:
    driver: bridge
    name: ${APP_NAME}-network
