version: '3.8'

services:
  backend-grpc-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: ${APP_NAME}-backend-grpc-server:${IMAGE_TAG:-latest}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - app-network
    environment:
      - PORT=${BACKEND_PORT}
    container_name: ${APP_NAME}-backend-grpc-server

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: ${APP_NAME}-frontend:${IMAGE_TAG:-latest}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app-network
    environment:
      # WICHTIG: Kein http:// und kein trailing slash für gRPC!
      - GRPC_SERVER_URL=${BACKEND_HOST}:${BACKEND_PORT}
      - PORT=${FRONTEND_PORT}
    depends_on:
      - backend-grpc-server
    container_name: ${APP_NAME}-frontend

networks:
  app-network:
    driver: bridge
    name: ${APP_NAME}-network