version: '3.8'

services:
  backend-grpc-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: ${APP_NAME}-backend-grpc-server
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${GRPC_WEB_PORT}:${GRPC_WEB_PORT}"
    networks:
      - app-network
    environment:
      - PORT=${BACKEND_PORT}
      - WEB_PORT=${GRPC_WEB_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
      - GRPC_WEB_URL=${GRPC_WEB_URL}
      - DEEPL_API_KEY=${DEEPL_API_KEY}
    container_name: ${APP_NAME}-backend-grpc-server
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - VUE_APP_GRPC_WEB_URL=${GRPC_WEB_URL}
        - NODE_ENV=production
    image: ${APP_NAME}-frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app-network
    environment:
      # Fix: Add the missing environment variables for Nginx template
      - PORT=${FRONTEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PROTOCOL=${FRONTEND_PROTOCOL}
      - BASE_URL=${BASE_URL}
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
      - BACKEND_HOST=backend-grpc-server  # Fix: Use service name for internal communication
      - GRPC_WEB_PORT=${GRPC_WEB_PORT}
    depends_on:
      - backend-grpc-server
    container_name: ${APP_NAME}-frontend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
    name: ${APP_NAME}-network
