root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/server"
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "pb", "node_modules", "proto"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*\\.pb\\.go$"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  # Wichtig: Überwache diese Verzeichnisse für Änderungen
  include_dir = ["cmd", "internal", "handler", "service", "pkg"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "500ms"
  log = "build-errors.log"
  # Wichtig für Docker: Polling aktivieren
  poll = true
  poll_interval = 1000
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
