/**
 * @fileoverview gRPC-Web generated client stub for notification
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.1
// source: notification.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.notification = require('./notification_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.notification.NotificationServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.notification.NotificationServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.notification.GetNotificationRequest,
 *   !proto.notification.GetNotificationResponse>}
 */
const methodDescriptor_NotificationService_GetNotification = new grpc.web.MethodDescriptor(
  '/notification.NotificationService/GetNotification',
  grpc.web.MethodType.UNARY,
  proto.notification.GetNotificationRequest,
  proto.notification.GetNotificationResponse,
  /**
   * @param {!proto.notification.GetNotificationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.notification.GetNotificationResponse.deserializeBinary
);


/**
 * @param {!proto.notification.GetNotificationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.notification.GetNotificationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.notification.GetNotificationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.notification.NotificationServiceClient.prototype.getNotification =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/notification.NotificationService/GetNotification',
      request,
      metadata || {},
      methodDescriptor_NotificationService_GetNotification,
      callback);
};


/**
 * @param {!proto.notification.GetNotificationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.notification.GetNotificationResponse>}
 *     Promise that resolves to the response
 */
proto.notification.NotificationServicePromiseClient.prototype.getNotification =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/notification.NotificationService/GetNotification',
      request,
      metadata || {},
      methodDescriptor_NotificationService_GetNotification);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.notification.CreateNotificationRequest,
 *   !proto.notification.CreateNotificationResponse>}
 */
const methodDescriptor_NotificationService_CreateNotification = new grpc.web.MethodDescriptor(
  '/notification.NotificationService/CreateNotification',
  grpc.web.MethodType.UNARY,
  proto.notification.CreateNotificationRequest,
  proto.notification.CreateNotificationResponse,
  /**
   * @param {!proto.notification.CreateNotificationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.notification.CreateNotificationResponse.deserializeBinary
);


/**
 * @param {!proto.notification.CreateNotificationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.notification.CreateNotificationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.notification.CreateNotificationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.notification.NotificationServiceClient.prototype.createNotification =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/notification.NotificationService/CreateNotification',
      request,
      metadata || {},
      methodDescriptor_NotificationService_CreateNotification,
      callback);
};


/**
 * @param {!proto.notification.CreateNotificationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.notification.CreateNotificationResponse>}
 *     Promise that resolves to the response
 */
proto.notification.NotificationServicePromiseClient.prototype.createNotification =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/notification.NotificationService/CreateNotification',
      request,
      metadata || {},
      methodDescriptor_NotificationService_CreateNotification);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.notification.ListNotificationsRequest,
 *   !proto.notification.ListNotificationsResponse>}
 */
const methodDescriptor_NotificationService_ListNotifications = new grpc.web.MethodDescriptor(
  '/notification.NotificationService/ListNotifications',
  grpc.web.MethodType.UNARY,
  proto.notification.ListNotificationsRequest,
  proto.notification.ListNotificationsResponse,
  /**
   * @param {!proto.notification.ListNotificationsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.notification.ListNotificationsResponse.deserializeBinary
);


/**
 * @param {!proto.notification.ListNotificationsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.notification.ListNotificationsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.notification.ListNotificationsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.notification.NotificationServiceClient.prototype.listNotifications =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/notification.NotificationService/ListNotifications',
      request,
      metadata || {},
      methodDescriptor_NotificationService_ListNotifications,
      callback);
};


/**
 * @param {!proto.notification.ListNotificationsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.notification.ListNotificationsResponse>}
 *     Promise that resolves to the response
 */
proto.notification.NotificationServicePromiseClient.prototype.listNotifications =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/notification.NotificationService/ListNotifications',
      request,
      metadata || {},
      methodDescriptor_NotificationService_ListNotifications);
};


module.exports = proto.notification;

